# Config file for automatic testing at travis-ci.org

language: python
# python:
#   - 3.6
#   - 3.5
#   - 3.4
#   - 2.7
  # PyPy versions
  # - "pypy"   # currently Python 2.7.13, PyPy 7.1.1
  # - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0

# Replaces the above.
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38

# Install package dependencies.
install: pip install -r requirements.txt --use-mirrors

# Install Setupt Tools and Tox.
# install: pip install -U setuptools
# install: pip install -U tox-travis

# Force setuptools to get updated BEFORE tox.
install: pip install -U setuptools & pip install tox-travis
# install: pip install -U setuptools & pip install tox & pip install tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

notifications:
  email: false

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: genomeDashboard
  password:
    secure: g3n0m3d@$hb0@rd
  on:
    tags: true
    repo: genome-dashboard/genome-dashboard-python
    python: 3.6
